<a href="https://colab.research.google.com/github/qtbun0w0/My-first-Repo/blob/main/np_vs_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NP Arrays

In [ ]:
import torch
import numpy as np

np1 = np.random.rand(3,4)

print(np1,'\n')
np1.dtype

[[0.27998415 0.79290269 0.47798795 0.50484233]
 [0.85903244 0.31877064 0.43524063 0.68945448]
 [0.75423154 0.70586811 0.06908359 0.7118617 ]] 



dtype('float64')

Tensors

In [ ]:
tensor34 = torch.randn(3,4)

print(tensor34,'\n')
tensor34.dtype

tensor([[ 1.0840,  0.0736,  0.4563,  0.3428],
        [ 2.6328, -2.1895, -0.8844,  1.5775],
        [-1.8794, -2.3830,  1.7202,  0.0190]]) 



torch.float32

In [ ]:
tensor234 = torch.zeros(2,3,4)

tensor234

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [ ]:
mytensor = torch.tensor(np1)

mytensor

tensor([[0.2800, 0.7929, 0.4780, 0.5048],
        [0.8590, 0.3188, 0.4352, 0.6895],
        [0.7542, 0.7059, 0.0691, 0.7119]], dtype=torch.float64)